server:
  port: 8082
spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: payment-group-test
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  data:
    mongodb:
      uri: mongodb://localhost:27017/order_nosql
  datasource:
    url: jdbc:postgresql://localhost:5432/order_db
    username: postgres
    password: postgres
external:
  api:
    timeout:
      connection: 1s
      response: 1s
    viacep:
      base-url: https://viacep.com.br
    exchange:
      base-url: https://economia.awesomeapi.com.br